[package]
name = "mlog-pico"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
embedded-alloc = "0.6.0"
embedded-hal = "1.0.0"
mindustry-rs = { path = "../mindustry-rs", default-features = false, features = ["no_std"] }
panic-persist = "0.3.0"
portable-atomic = { version = "1.11.1", features = ["critical-section"] }
rp-pico = "0.9.0"
spin = { version = "0.9.8", default-features = false, features = ["portable_atomic"] }
widestring = { version = "1.2.0", default-features = false }
