[alias]
br = "build --release"
rr = "run --release"

build-pico2 = [
    "build",
    "--target=thumbv8m.main-none-eabihf",
    "--no-default-features",
    "--features=pico2",
]
br2 = "build-pico2 --release"
run-pico2 = [
    "run",
    "--target=thumbv8m.main-none-eabihf",
    "--no-default-features",
    "--features=pico2",
]
rr2 = "run-pico2 --release"

[build]
# Set the default target to match the Cortex-M0+ in the RP2040
target = "thumbv6m-none-eabi"

# pico 1
[target.thumbv6m-none-eabi]
runner = "elf2uf2-rs --deploy --serial"

# pico 2
[target.thumbv8m.main-none-eabihf]
# https://github.com/JoNil/elf2uf2-rs/pull/39
runner = "elf2uf2-rs --deploy --serial --family 0xe48bff59"
